### PR TITLE
Added Hello World for Crystal

### PR DESCRIPTION
**Pull request by langee99**

### CODE REVIEW

**Review by sbshah97 — CHANGES_REQUESTED** [review]
Reference the Issue in the PR Description using the
`#` value! Ping me if you don't get it yet!

**Comment by langee99** [comment]
@salman-bhai There's no issue for me to reference unless you want me to create one? Also would you mind if I closed and reopened on Oct 1 to get credit for hacktoberfest?

**Comment by sbshah97** [comment]
Create an Issue and then reference it here! @langee99 No problem with the October 1 thing! You can create the Issue on October 1 itself!

**Comment by sbshah97** [comment]
@langee99 please create an Issue and reference it so that I can merge the PR

**Pull request closed without merging**
