### PR TITLE
Update readme python3

### PR DESCRIPTION
**Pull request by Tony133**
Install python3 for Mac OS via homebrew

### CODE REVIEW

**Review by sbshah97 — CHANGES_REQUESTED** [review]
I see three files have been changed here, but PR Description refers to one! Kindly reference the Issues that you are trying to resolve and next time onwards it's prefereable to send one Pull Request rather than Parallel Requests merging almost the same files!

**Comment by sbshah97** [comment]
Any problems here?

**Comment by sbshah97** [comment]
Any updates @Tony133

**Comment by Tony133** [comment]
Hello, sorry if I did not answer you, but I did not have time in these two days.
If you want to do the merge, if I think of adding more things I make a new pull request.

**Review by sbshah97 — APPROVED** [review]

**Pull request merged**
