### PR TITLE
Update readme ruby

### PR DESCRIPTION
**Pull request by Tony133**
Alternative install Ruby for Mac OS

### CODE REVIEW

**Review by sbshah97 — CHANGES_REQUESTED** [review]
Hi kindly reference the Issue that you are resolving with the PR Description as `closes #<Issue-Number> `. I'll merge the PR then!

**Comment by sbshah97** [comment]
Any problems here?

**Comment by sbshah97** [comment]
Any updates @Tony133

**Comment by Tony133** [comment]
Hello, sorry if I did not answer you, but I did not have time in these two days.
If you want to do the merge, if I think of adding more things I make a new pull request

**Review by sbshah97 — APPROVED** [review]

**Pull request merged**
